sudo: required
language: python

compiler:
  - clang

env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create -n test-env --file https://data.qiime2.org/distro/core/qiime2-2017.5-conda-linux-64.txt python=$PYTHON_VERSION nose flake8
  - source activate test-env
  # needed for the hdf5 dev tools
  - conda install --yes -c conda-forge hdf5 h5py
  - sed -i 's/^CXXBASE=.*/CXXBASE=clang++/' `which h5c++`
  - sed -i 's/^CXXLINKERBASE=.*/CXXLINKERBASE=clang++/' `which h5c++`
  - git clone https://github.com/qiime2/q2lint
  - pip install . 
script:
  - flake8 q2_state_unifrac setup.py
  - python q2lint/q2lint.py
  - qiime state-unifrac unweighted --i-table table.qza --i-phylogeny tree.qza --o-distance-matrix ssu_result.qza
  - qiime diversity beta-phylogenetic --p-metric unweighted_unifrac --i-table table.qza --i-phylogeny tree.qza --o-distance-matrix sk_result.qza
  - python compare_dms.py ssu_result.qza sk_result.qza
